# 1) Importing the datasets

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data_yelp = pd.read_csv('yelp_labelled.txt',sep='\t',header=None)

In [3]:
data_yelp.head()

# dataframe contains 2 cols
# review and sentiment
# 0- Negative, 1- Positive review

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [4]:
# Assign column names
column_name = ['Review','Sentiment']
data_yelp.columns = column_name

In [5]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [6]:
data_yelp.shape

# 1000 rows, 2 columns (Sentiments)

(1000, 2)

In [7]:
#-------reading another set of data--------------#

In [8]:
data_amazon = pd.read_csv('amazon_cells_labelled.txt',sep='\t',header=None)
data_amazon.head()

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [9]:
data_amazon.columns = column_name

In [10]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [11]:
data_amazon.shape

(1000, 2)

In [12]:
#--------read another set of data-----------#

In [13]:
data_imdb = pd.read_csv('imdb_labelled.txt',sep='\t',header=None)
data_imdb.head()

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

In [14]:
data_imdb.columns = column_name

In [18]:
data_imdb.shape

(748, 2)

### -- append all the 3 dataset into a single dataframe

In [16]:
data = data_yelp.append([data_amazon,data_imdb],ignore_index=True)
data.shape

(2748, 2)

In [19]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

### -- check distribution of sentiments

In [21]:
data['Sentiment'].value_counts()

# 1386 positive reviews
# 1362 negative reviewss

1    1386
0    1362
Name: Sentiment, dtype: int64

In [22]:
# check for null values
data.isnull().sum()

#no null values in the data

Review       0
Sentiment    0
dtype: int64

### -- seggreagate the dataframe into 2 dataset
#### ---- 'Review' is input dataset, 'Sentiment' is output dataset

In [23]:
x = data['Review']
y = data['Sentiment']

# 2) Data Cleaning

In [24]:
# use SpaCy 
# here we will remove stopwords, punctuations
# apply lemmatization

### Create a function to clean the data

In [25]:
# import punctuation from string
import string
punct = string.punctuation
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [26]:
from spacy.lang.en.stop_words import STOP_WORDS

In [27]:
# load all stopwords from Spacy in list
stopwords = list(STOP_WORDS) 
stopwords

['serious',
 'not',
 'meanwhile',
 'was',
 'something',
 'already',
 'along',
 '’ve',
 'get',
 'formerly',
 'unless',
 "'s",
 'does',
 'nevertheless',
 'above',
 'ourselves',
 'any',
 'about',
 'twelve',
 'none',
 'thus',
 'really',
 "'d",
 'against',
 'whereupon',
 'former',
 'in',
 'thence',
 'latter',
 'noone',
 'n‘t',
 'make',
 'everywhere',
 'ever',
 'rather',
 'behind',
 'these',
 'by',
 'down',
 'within',
 'therefore',
 'wherein',
 'thereafter',
 'yet',
 'seeming',
 'seems',
 'a',
 'at',
 'together',
 'forty',
 'have',
 'otherwise',
 'whenever',
 'is',
 'moreover',
 'we',
 'keep',
 'himself',
 'even',
 'whence',
 'upon',
 'someone',
 'around',
 '‘m',
 'just',
 'you',
 '’d',
 'ours',
 'for',
 '’m',
 'how',
 'several',
 'ten',
 'am',
 'hence',
 'thereby',
 'will',
 'became',
 'mine',
 'the',
 'well',
 'however',
 'seemed',
 'seem',
 'hundred',
 'empty',
 'due',
 'would',
 'thru',
 'move',
 'cannot',
 'either',
 'full',
 'latterly',
 '‘d',
 'own',
 'whose',
 'eleven',
 'whereafter'

In [29]:
# creating a function for data cleaning

# if root form of that word is not PRONOUN then it is going to convert that into lower form
# and if that word is a proper noun, then we are directly taking lower form, because there is no lemma;

In [32]:
import spacy

nlp = spacy.load('en_core_web_sm')
def text_data_cleaning(sentence):
    
    #initialize Spacy model and apply sentence
    doc = nlp(sentence)
    
    tokens = [] # list of tokens
    
    # this loop will load every single token
    for token in doc:
        if token.lemma_ != '-PRON-':
            temp = token.lemma_.lower().strip()
        else:
            temp = token.lower_
        tokens.append(temp)
        
    cleaned_tokens=[]
    # this loop will going to remove all the punctuations, stopwords
    for token in tokens:
        if token not in stopwords and token not in punct:
            cleaned_tokens.append(token)
    return cleaned_tokens

In [33]:
# Example
text_data_cleaning("Hello all, It's a beautiful day outside there!")

# stopwords and punctuations removed

['hello', 'beautiful', 'day', 'outside']

# 3) Vectorization Feature Engineering (TF-IDF)

In [35]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [ ]:
# tfidf is another feature-encoding technique
# where we are going to convert all our ori terms/ ori documents / reviews into kind of some sort of numbers


# TF-IDF = TF (T d) * IDF (T)

# TF = Term frequency - number of times term t appears in a doc, d
# IDF = Inverse Document Frequency - how much a terms occur across all documents
# ---- log((1+n)/(1+df(d,t))) +1 
# ---- df = Document Frequency of the term t


# the above formula is calculating how much important individual word in a individual document


In [36]:
# when calling Tfidf, we pass in the predefined function above for cleaning
# tokenier = text_data_cleaning, meaning tokenization will be done according to this function

tfidf = TfidfVectorizer(tokenizer=text_data_cleaning)

In [37]:
# Define SVM model
classifier = LinearSVC()

# 3) Train the model

### -- Splitting the dataset into the Train and Test set

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size =0.2,random_state=0)


In [39]:
X_train.shape,X_test.shape

#2198 samples in training dataset and 550 in test dataset

((2198,), (550,))

In [41]:
X_train.head()

2572    An Italian reviewer called this "a small, grea...
526                          And it was way to expensive.
1509    As an earlier review noted, plug in this charg...
144     Nice blanket of moz over top but i feel like t...
2483    The film gives meaning to the phrase, "Never i...
Name: Review, dtype: object

### -- Fit the X_train and y_train

In [42]:
clf = Pipeline([('tfidf',tfidf),('clf',classifier)])

# it will first do vectorization and then it will do classification

In [43]:
clf.fit(X_train,y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x00000287ED070840>)),
                ('clf', LinearSVC())])

In [44]:
# in this we don't need to prepare the dataset for testing(x_test)

# 4) Predict the test set results

In [45]:
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [46]:
y_pred = clf.predict(X_test)

In [47]:
# confusion matrix
confusion_matrix(y_test,y_pred)

array([[204,  75],
       [ 49, 222]], dtype=int64)

In [48]:
# classification report
print(classification_report(y_test,y_pred))

# we are getting almost 77% accuracy

              precision    recall  f1-score   support

           0       0.81      0.73      0.77       279
           1       0.75      0.82      0.78       271

    accuracy                           0.77       550
   macro avg       0.78      0.78      0.77       550
weighted avg       0.78      0.77      0.77       550



In [49]:
accuracy_score(y_test,y_pred)

0.7745454545454545

## use the trained model to make prediction

In [51]:
clf.predict(["Wow, I am learning Natural Language Processing in fun fashion!"])

array([1], dtype=int64)

In [52]:
# output is 1 , positive

In [53]:
clf.predict(["It's hard to learn something"])

array([0], dtype=int64)